//------------------------------------------------------------------------------
// <auto-generated>
//    Ten kod źródłowy został wygenerowany na podstawie szablonu.
//
//    Ręczne modyfikacje tego pliku mogą spowodować nieoczekiwane zachowanie aplikacji.
//    Ręczne modyfikacje tego pliku zostaną zastąpione w przypadku ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AILabForum.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        //model konta użytkownika wygenerowany z bazy danych
        public int id { get; set; }
        [DisplayName("Login: ")]
        [Required(ErrorMessage = "Wprowadź nazwę użytkownika !!!")]
        public string login { get; set; }
        [DisplayName("Hasło: ")]
        [DataType(DataType.Password)]
        [Required(ErrorMessage = "Wprowadź hasło !!!")]
        public string password { get; set; }
        public string imie { get; set; }
        public string email { get; set; }
        public System.DateTime data_urodzenia { get; set; }
        public string miejscowosc { get; set; }
        public string LoginErrorMessage { get; set; }
    }
}
